name: Simple CI Demo

on:
  push:
    branches:
      - main

jobs:
  check-project:
    runs-on: ubuntu-latest

    steps:
      - name: Download Repository
        uses: actions/checkout@v4

      - name: Show Files
        run: ls -la

      - name: Check index.html Exists
        run: test -f index.html

      - name: Check style.css Exists
        run: test -f css/styles.css

      - name: Check script.js Exists
        run: test -f app.js

      - name: Success Message
        run: echo "Project looks good! CI Passed."
